package __backup__;

/**
 * To represent how the syntactic change is conducted, which
 * is used to customize the mutation to be seeded in program.
 * @author yukimula
 */
public enum MutationMode {
	
	/* statement mode */
	/** mode for trap_on_statement() mode **/ 				TRAP_ON_STMT,
	/** trap_on_true(predicate) **/ 						TRAP_ON_TRUE,
	/** trap_on_false(predicate) **/ 						TRAP_ON_FALSE,
	/** trap_on_case(e, v) **/								VTRAP_ON_CASE,
	/** trap_for_times(n) **/								VTRAP_FOR_TIMES,
	/** statement |--> {} **/ 								DELETE_STATEMENT,
	/** break |--> continue **/								REP_BY_CONTINUE,
	/** continue |--> break **/								REP_BY_BREAK,
	/** while |--> do...while **/							REP_BY_DO_WHILE,
	/** do...while |--> while **/							REP_BY_WHILE,
	
	/* increment-operator mutation */
	/** x++ |--> ++x **/									POST_PREV_INC,
	/** ++x |--> x++ **/									PREV_POST_INC,
	/** x++ |--> x-- **/									POST_INC_DEC,
	/** ++x |--> --x **/									PREV_INC_DEC,
	/** x-- |--> --x **/									POST_PREV_DEC,
	/** --x |--> x-- **/									PREV_POST_DEC,
	/** x-- |--> x++ **/									POST_DEC_INC,
	/** --x |--> ++x **/									PREV_DEC_INC,
	/** x |--> ++x **/										PREV_INC_INS,
	/** x |--> --x **/										PREV_DEC_INS,
	/** x |--> x++ **/										POST_INC_INS,
	/** x |--> x-- **/										POST_DEC_INS,
	
	/* negative-insertion mutation */
	/** expr |--> !(expr) **/								NEG_BOOLEAN,
	/** expr |--> ~(expr) **/								NEG_BITWISE,
	
	/* negative-deletion mutation */
	/** -expr |--> expr **/									ANG_DELETE,
	/** ~expr |--> expr **/									BNG_DELETE,
	/** !expr |--> expr **/									LNG_DELETE,
	
	
	/* arithmetic-operator mutation (OAAN) */
	/** (+, -) **/											ADD_SUB,
	/** (+, *) **/											ADD_MUL,
	/** (+, /) **/											ADD_DIV,
	/** (+, %) **/											ADD_MOD,
	/** (-, +) **/											SUB_ADD,
	/** (-, *) **/											SUB_MUL,
	/** (-, /) **/											SUB_DIV,
	/** (-, %) **/											SUB_MOD,
	/** (*, +) **/											MUL_ADD,
	/** (*, -) **/											MUL_SUB,
	/** (*, /) **/											MUL_DIV,
	/** (*, %) **/											MUL_MOD,
	/** (/, +) **/											DIV_ADD,
	/** (/, -) **/											DIV_SUB,
	/** (/, *) **/											DIV_MUL,
	/** (/, %) **/											DIV_MOD,
	/** (%, +) **/											MOD_ADD,
	/** (%, -) **/											MOD_SUB,
	/** (%, *) **/											MOD_MUL,
	/** (%, /) **/											MOD_DIV,
	/* arithmetic-bitwise mutation (OABN) */
	/** (+, &) **/											ADD_BAN,
	/** (+, |) **/											ADD_BOR,
	/** (+, ^) **/											ADD_BXR,
	/** (-, &) **/											SUB_BAN,
	/** (-, |) **/											SUB_BOR,
	/** (-, ^) **/											SUB_BXR,
	/** (*, &) **/											MUL_BAN,
	/** (*, |) **/											MUL_BOR,
	/** (*, ^) **/											MUL_BXR,
	/** (/, &) **/											DIV_BAN,
	/** (/, |) **/											DIV_BOR,
	/** (/, ^) **/											DIV_BXR,
	/** (%, &) **/											MOD_BAN,
	/** (%, |) **/											MOD_BOR,
	/** (%, ^) **/											MOD_BXR,
	/* arithmetic-logical mutation (OALN) */
	/** (+, &&) **/											ADD_LAN,
	/** (+, ||) **/											ADD_LOR,
	/** (-, &&) **/											SUB_LAN,
	/** (-, ||) **/											SUB_LOR,
	/** (*, &&) **/											MUL_LAN,
	/** (*, ||) **/											MUL_LOR,
	/** (/, &&) **/											DIV_LAN,
	/** (/, ||) **/											DIV_LOR,
	/** (%, &&) **/											MOD_LAN,
	/** (%, ||) **/											MOD_LOR,
	/* arithmetic-relation mutation (OARN) */
	/** (+, >)  **/											ADD_GRT,
	/** (+, >=) **/											ADD_GRE,
	/** (+, <)  **/											ADD_SMT,
	/** (+, <=) **/											ADD_SME,
	/** (+, ==) **/											ADD_EQV,
	/** (+, !=) **/											ADD_NEQ,
	/** (-, >)  **/											SUB_GRT,
	/** (-, >=) **/											SUB_GRE,
	/** (-, <)  **/											SUB_SMT,
	/** (-, <=) **/											SUB_SME,
	/** (-, ==) **/											SUB_EQV,
	/** (-, !=) **/											SUB_NEQ,
	/** (*, >)  **/											MUL_GRT,
	/** (*, >=) **/											MUL_GRE,
	/** (*, <)  **/											MUL_SMT,
	/** (*, <=) **/											MUL_SME,
	/** (*, ==) **/											MUL_EQV,
	/** (*, !=) **/											MUL_NEQ,
	/** (/, >)  **/											DIV_GRT,
	/** (/, >=) **/											DIV_GRE,
	/** (/, <)  **/											DIV_SMT,
	/** (/, <=) **/											DIV_SME,
	/** (/, ==) **/											DIV_EQV,
	/** (/, !=) **/											DIV_NEQ,
	/** (%, >)  **/											MOD_GRT,
	/** (%, >=) **/											MOD_GRE,
	/** (%, <)  **/											MOD_SMT,
	/** (%, <=) **/											MOD_SME,
	/** (%, ==) **/											MOD_EQV,
	/** (%, !=) **/											MOD_NEQ,
	/* arithmetic-shifting operator (OASN) */
	/** (+, >>) **/											ADD_RSH,
	/** (+, <<) **/											ADD_LSH,
	/** (-, >>) **/											SUB_RSH,
	/** (-, <<) **/											SUB_LSH,
	/** (*, >>) **/											MUL_RSH,
	/** (*, <<) **/											MUL_LSH,
	/** (/, >>) **/											DIV_RSH,
	/** (/, <<) **/											DIV_LSH,
	/** (%, >>) **/											MOD_RSH,
	/** (%, <<) **/											MOD_LSH,
	
	/* bitwise-arithmetic operator (OBAN) */ 
	/** (&, +) **/											BAN_ADD,
	/** (&, -) **/											BAN_SUB,
	/** (&, *) **/											BAN_MUL,
	/** (&, /) **/											BAN_DIV,
	/** (&, %) **/											BAN_MOD,
	/** (|, +) **/											BOR_ADD,
	/** (|, -) **/											BOR_SUB,
	/** (|, *) **/											BOR_MUL,
	/** (|, /) **/											BOR_DIV,
	/** (|, %) **/											BOR_MOD,
	/** (^, +) **/											BXR_ADD,
	/** (^, -) **/											BXR_SUB,
	/** (^, *) **/											BXR_MUL,
	/** (^, /) **/											BXR_DIV,
	/** (^, %) **/											BXR_MOD,
	/* bitwise-operator mutation (OBBN) */
	/** (&, |) **/											BAN_BOR,
	/** (&, ^) **/											BAN_BXR,
	/** (|, &) **/											BOR_BAN,
	/** (|, ^) **/											BOR_BXR,
	/** (^, &) **/											BXR_BAN,
	/** (^, |) **/											BXR_BOR,
	/* bitwise-logical mutation (OBLN) */
	/** (&, &&) **/											BAN_LAN,
	/** (&, ||) **/											BAN_LOR,
	/** (|, &&) **/											BOR_LAN,
	/** (|, ||) **/											BOR_LOR,
	/** (^, &&) **/											BXR_LAN,
	/** (^, ||) **/											BXR_LOR,
	/* bitwise-relation mutation (OBRN) */
	/** (&, >)  **/											BAN_GRT,
	/** (&, >=) **/											BAN_GRE,
	/** (&, ==) **/											BAN_EQV,
	/** (&, !=) **/											BAN_NEQ,
	/** (&, <)  **/											BAN_SMT,
	/** (&, <=) **/											BAN_SME,
	/** (|, >)  **/											BOR_GRT,
	/** (|, >=) **/											BOR_GRE,
	/** (|, ==) **/											BOR_EQV,
	/** (|, !=) **/											BOR_NEQ,
	/** (|, <)  **/											BOR_SMT,
	/** (|, <=) **/											BOR_SME,
	/** (^, >)  **/											BXR_GRT,
	/** (^, >=) **/											BXR_GRE,
	/** (^, ==) **/											BXR_EQV,
	/** (^, !=) **/											BXR_NEQ,
	/** (^, <)  **/											BXR_SMT,
	/** (^, <=) **/											BXR_SME,
	/* bitwise-shifting mutation (OBSN) */
	/** (&, <<) **/											BAN_LSH,
	/** (&, >>) **/											BAN_RSH,
	/** (|, <<) **/											BOR_LSH,
	/** (|, >>) **/											BOR_RSH,
	/** (^, <<) **/											BXR_LSH,
	/** (^, >>) **/											BXR_RSH,
	
	/* logical-arithmetic mutation (OLAN) */
	/** (&&, +) **/											LAN_ADD,
	/** (&&, -) **/											LAN_SUB,
	/** (&&, *) **/											LAN_MUL,
	/** (&&, /) **/											LAN_DIV,
	/** (&&, %) **/											LAN_MOD,
	/** (||, +) **/											LOR_ADD,
	/** (||, -) **/											LOR_SUB,
	/** (||, *) **/											LOR_MUL,
	/** (||, /) **/											LOR_DIV,
	/** (||, %) **/											LOR_MOD,
	/* logical-bitwise mutation (OLBN) */
	/** (&&, &) **/											LAN_BAN,
	/** (&&, |) **/											LAN_BOR,
	/** (&&, ^) **/											LAN_BXR,
	/** (||, &) **/											LOR_BAN,
	/** (||, |) **/											LOR_BOR,
	/** (||, ^) **/											LOR_BXR,
	/* logical-operator mutation (OLLN) */
	/** (&&, ||) **/										LAN_LOR,
	/** (||, &&) **/										LOR_LAN,
	/* logical-relation mutation (OLRN) */
	/** (&&, >)  **/										LAN_GRT,
	/** (&&, >=) **/										LAN_GRE,
	/** (&&, ==) **/										LAN_EQV,
	/** (&&, !=) **/										LAN_NEQ,
	/** (&&, <) **/											LAN_SMT,
	/** (&&, <=) **/										LAN_SME,
	/** (||, >)  **/										LOR_GRT,
	/** (||, >=) **/										LOR_GRE,
	/** (||, ==) **/										LOR_EQV,
	/** (||, !=) **/										LOR_NEQ,
	/** (||, <) **/											LOR_SMT,
	/** (||, <=) **/										LOR_SME,
	/* logical-shifting mutation (OLSN) */
	/** (&&, <<) **/										LAN_LSH,
	/** (&&, >>) **/										LAN_RSH,
	/** (||, <<) **/										LOR_LSH,
	/** (||, >>) **/										LOR_RSH,
	
	/* relation-arithmetic mutation (ORAN) */
	/** (>, +) **/											GRT_ADD,
	/** (>, -) **/											GRT_SUB,
	/** (>, *) **/											GRT_MUL,
	/** (>, /) **/											GRT_DIV,
	/** (>, %) **/											GRT_MOD,
	/** (>=, +) **/											GRE_ADD,
	/** (>=, -) **/											GRE_SUB,
	/** (>=, *) **/											GRE_MUL,
	/** (>=, /) **/											GRE_DIV,
	/** (>=, %) **/											GRE_MOD,
	/** (==, +) **/											EQV_ADD,
	/** (==, -) **/											EQV_SUB,
	/** (==, *) **/											EQV_MUL,
	/** (==, /) **/											EQV_DIV,
	/** (==, %) **/											EQV_MOD,
	/** (!=, +) **/											NEQ_ADD,
	/** (!=, -) **/											NEQ_SUB,
	/** (!=, *) **/											NEQ_MUL,
	/** (!=, /) **/											NEQ_DIV,
	/** (!=, %) **/											NEQ_MOD,
	/** (<, +) **/											SMT_ADD,
	/** (<, -) **/											SMT_SUB,
	/** (<, *) **/											SMT_MUL,
	/** (<, /) **/											SMT_DIV,
	/** (<, %) **/											SMT_MOD,
	/** (<=, +) **/											SME_ADD,
	/** (<=, -) **/											SME_SUB,
	/** (<=, *) **/											SME_MUL,
	/** (<=, /) **/											SME_DIV,
	/** (<=, %) **/											SME_MOD,
	/* relation-bitwise mutation (ORBN) */
	/** (>, &) **/											GRT_BAN,
	/** (>, |) **/											GRT_BOR,
	/** (>, ^) **/											GRT_BXR,
	/** (>=, &) **/											GRE_BAN,
	/** (>=, |) **/											GRE_BOR,
	/** (>=, ^) **/											GRE_BXR,
	/** (==, &) **/											EQV_BAN,
	/** (==, |) **/											EQV_BOR,
	/** (==, ^) **/											EQV_BXR,
	/** (!=, &) **/											NEQ_BAN,
	/** (!=, |) **/											NEQ_BOR,
	/** (!=, ^) **/											NEQ_BXR,
	/** (<, &) **/											SMT_BAN,
	/** (<, |) **/											SMT_BOR,
	/** (<, ^) **/											SMT_BXR,
	/** (<=, &) **/											SME_BAN,
	/** (<=, |) **/											SME_BOR,
	/** (<=, ^) **/											SME_BXR,
	/* relation-logical mutation (ORLN) */
	/** (>, &&) **/											GRT_LAN,
	/** (>, ||) **/											GRT_LOR,
	/** (>=, &&) **/										GRE_LAN,
	/** (>=, ||) **/										GRE_LOR,
	/** (==, &&) **/										EQV_LAN,
	/** (==, ||) **/										EQV_LOR,
	/** (!=, &&) **/										NEQ_LAN,
	/** (!=, ||) **/										NEQ_LOR,
	/** (<, &&) **/											SMT_LAN,
	/** (<, ||) **/											SMT_LOR,
	/** (<=, &&) **/										SME_LAN,
	/** (<=, ||) **/										SME_LOR,
	/* relation-operator mutation (ORRN) */
	/** (>, >=) **/											GRT_GRE,
	/** (>, ==) **/											GRT_EQV,
	/** (>, !=) **/											GRT_NEQ,
	/** (>, <)  **/											GRT_SMT,
	/** (>, <=) **/											GRT_SME,
	/** (>=, >) **/											GRE_GRT,
	/** (>=, ==)**/											GRE_EQV,
	/** (>=, !=)**/											GRE_NEQ,
	/** (>=, <) **/											GRE_SMT,
	/** (>=, <=)**/											GRE_SME,
	/** (==,>)  **/											EQV_GRT,
	/** (==,>=) **/											EQV_GRE,
	/** (==,!=) **/											EQV_NEQ,
	/** (==,<)  **/											EQV_SMT,
	/** (==,<=) **/											EQV_SME,
	/** (!=, >)  **/										NEQ_GRT,
	/** (!=,>=) **/											NEQ_GRE,
	/** (!=,==) **/											NEQ_EQV,
	/** (!=, <)  **/										NEQ_SMT,
	/** (!=,<=) **/											NEQ_SME,
	/** (<, >)  **/											SMT_GRT,
	/** (<, >=) **/											SMT_GRE,
	/** (<, ==) **/											SMT_EQV,
	/** (<, !=) **/											SMT_NEQ,
	/** (<, <=) **/											SMT_SME,
	/** (<=,>)  **/											SME_GRT,
	/** (<=,>=) **/											SME_GRE,
	/** (<=,==) **/											SME_EQV,
	/** (<=,!=) **/											SME_NEQ,
	/** (<=,<)  **/											SME_SMT,
	/* relation-shifting mutation (ORSN) */
	/** (>, <<) **/											GRT_LSH,
	/** (>, >>) **/											GRT_RSH,
	/** (>=, <<) **/										GRE_LSH,
	/** (>=, >>) **/										GRE_RSH,
	/** (==, <<) **/										EQV_LSH,
	/** (==, >>) **/										EQV_RSH,
	/** (!=, <<) **/										NEQ_LSH,
	/** (!=, >>) **/										NEQ_RSH,
	/** (<, <<) **/											SMT_LSH,
	/** (<, >>) **/											SMT_RSH,
	/** (<=, <<) **/										SME_LSH,
	/** (<=, >>) **/										SME_RSH,
	
	/* shifting-arithmetic mutation (OSAN) */
	/** (<<, +) **/											LSH_ADD,
	/** (<<, -) **/											LSH_SUB,
	/** (<<, *) **/											LSH_MUL,
	/** (<<, /) **/											LSH_DIV,
	/** (<<, %) **/											LSH_MOD,
	/** (>>, +) **/											RSH_ADD,
	/** (>>, -) **/											RSH_SUB,
	/** (>>, *) **/											RSH_MUL,
	/** (>>, /) **/											RSH_DIV,
	/** (>>, %) **/											RSH_MOD,
	/* shifting-bitwise mutation (OSBN) */
	/** (<<, &) **/											LSH_BAN,
	/** (<<, |) **/											LSH_BOR,
	/** (<<, ^) **/											LSH_BXR,
	/** (>>, &) **/											RSH_BAN,
	/** (>>, |) **/											RSH_BOR,
	/** (>>, ^) **/											RSH_BXR,
	/* shifting-logical mutation (OSLN) */
	/** (<<, &&) **/										LSH_LAN,
	/** (<<, ||) **/										LSH_LOR,
	/** (>>, &&) **/										RSH_LAN,
	/** (>>, ||) **/										RSH_LOR,
	/* shifting-relation mutation (OSRN) */
	/** (<<, >)  **/										LSH_GRT,
	/** (<<, >=) **/										LSH_GRE,
	/** (<<, ==) **/										LSH_EQV,
	/** (<<, !=) **/										LSH_NEQ,
	/** (<<, <)  **/										LSH_SMT,
	/** (<<, <=) **/										LSH_SME,
	/** (>>, >)  **/										RSH_GRT,
	/** (>>, >=) **/										RSH_GRE,
	/** (>>, ==) **/										RSH_EQV,
	/** (>>, !=) **/										RSH_NEQ,
	/** (>>, <)  **/										RSH_SMT,
	/** (>>, <=) **/										RSH_SME,
	/* shifting-operator mutation (OSSN) */
	/** (<<, >>) **/										LSH_RSH,
	/** (>>, <<) **/										RSH_LSH,
	
	/* assign-arithmetic mutation (OEAA) */
	/** (=, +=) **/											ASG_ADD,
	/** (=, -=) **/											ASG_SUB,
	/** (=, *=) **/											ASG_MUL,
	/** (=, /=) **/											ASG_DIV,
	/** (=, %=) **/											ASG_MOD,
	/* assign-bitwise mutation (OEBA) */
	/** (=, &=) **/											ASG_BAN,
	/** (=, |=) **/											ASG_BOR,
	/** (=, ^=) **/											ASG_BXR,
	/* assign-shifting mutation (OESA) */
	/** (=, <<=) **/										ASG_LSH,
	/** (=, >>=) **/										ASG_RSH,
	
	/* arithmetic-assign mutation (OAAA) */
	/** (+=, -=) **/										ADD_SUB_A,
	/** (+=, *=) **/										ADD_MUL_A,
	/** (+=, /=) **/										ADD_DIV_A,
	/** (+=, %=) **/										ADD_MOD_A,
	/** (-=, +=) **/										SUB_ADD_A,
	/** (-=, *=) **/										SUB_MUL_A,
	/** (-=, /=) **/										SUB_DIV_A,
	/** (-=, %=) **/										SUB_MOD_A,
	/** (*=, +=) **/										MUL_ADD_A,
	/** (*=, -=) **/										MUL_SUB_A,
	/** (*=, /=) **/										MUL_DIV_A,
	/** (*=, %=) **/										MUL_MOD_A,
	/** (/=, +=) **/										DIV_ADD_A,
	/** (/=, -=) **/										DIV_SUB_A,
	/** (/=, *=) **/										DIV_MUL_A,
	/** (/=, %=) **/										DIV_MOD_A,
	/** (%=, +=) **/										MOD_ADD_A,
	/** (%=, -=) **/										MOD_SUB_A,
	/** (%=, *=) **/										MOD_MUL_A,
	/** (%=, %=) **/										MOD_DIV_A,
	/* arithmetic-bitwise-assignment (OABA) */
	/** (+=, &=) **/										ADD_BAN_A,
	/** (+=, |=) **/										ADD_BOR_A,
	/** (+=, ^=) **/										ADD_BXR_A,
	/** (-=, &=) **/										SUB_BAN_A,
	/** (-=, |=) **/										SUB_BOR_A,
	/** (-=, ^=) **/										SUB_BXR_A,
	/** (*=, &=) **/										MUL_BAN_A,
	/** (*=, |=) **/										MUL_BOR_A,
	/** (*=, ^=) **/										MUL_BXR_A,
	/** (/=, &=) **/										DIV_BAN_A,
	/** (/=, |=) **/										DIV_BOR_A,
	/** (/=, ^=) **/										DIV_BXR_A,
	/** (%=, &=) **/										MOD_BAN_A,
	/** (%=, |=) **/										MOD_BOR_A,
	/** (%=, ^=) **/										MOD_BXR_A,
	/* arithmetic-shifting-assignment (OASA) */
	/** (+=, <<=) **/										ADD_LSH_A,
	/** (+=, >>=) **/										ADD_RSH_A,
	/** (-=, <<=) **/										SUB_LSH_A,
	/** (-=, >>=) **/										SUB_RSH_A,
	/** (*=, <<=) **/										MUL_LSH_A,
	/** (*=, >>=) **/										MUL_RSH_A,
	/** (/=, <<=) **/										DIV_LSH_A,
	/** (/=, >>=) **/										DIV_RSH_A,
	/** (%=, <<=) **/										MOD_LSH_A,
	/** (%=, >>=) **/										MOD_RSH_A,
	
	/* bitwise-arithmetic-assignment (OBAA) */
	/** (&=, +=) **/										BAN_ADD_A,
	/** (&=, -=) **/										BAN_SUB_A,
	/** (&=, *=) **/										BAN_MUL_A,
	/** (&=, /=) **/										BAN_DIV_A,
	/** (&=, %=) **/										BAN_MOD_A,
	/** (|=, +=) **/										BOR_ADD_A,
	/** (|=, -=) **/										BOR_SUB_A,
	/** (|=, *=) **/										BOR_MUL_A,
	/** (|=, /=) **/										BOR_DIV_A,
	/** (|=, %=) **/										BOR_MOD_A,
	/** (^=, +=) **/										BXR_ADD_A,
	/** (^=, -=) **/										BXR_SUB_A,
	/** (^=, *=) **/										BXR_MUL_A,
	/** (^=, /=) **/										BXR_DIV_A,
	/** (^=, %=) **/										BXR_MOD_A,
	/* bitwise-bitwise-assignment (OBBA) */
	/** (&=, |=) **/										BAN_BOR_A,
	/** (&=, ^=) **/										BAN_BXR_A,
	/** (|=, &=) **/										BOR_BAN_A,
	/** (|=, ^=) **/										BOR_BXR_A,
	/** (^=, &=) **/										BXR_BAN_A,
	/** (^=, |=) **/										BXR_BOR_A,
	/* bitwise-shifting-assignment (OBSA) */
	/** (&=, <<=) **/										BAN_LSH_A,
	/** (&=, >>=) **/										BAN_RSH_A,
	/** (|=, <<=) **/										BOR_LSH_A,
	/** (|=, >>=) **/										BOR_RSH_A,
	/** (^=, <<=) **/										BXR_LSH_A,
	/** (^=, >>=) **/										BXR_RSH_A,
	
	/* shifting-arithmetic-assignment (OSAA) */
	/** (<<=, +=) **/										LSH_ADD_A,
	/** (<<=, -=) **/										LSH_SUB_A,
	/** (<<=, *=) **/										LSH_MUL_A,
	/** (<<=, /=) **/										LSH_DIV_A,
	/** (<<=, %=) **/										LSH_MOD_A,
	/** (>>=, +=) **/										RSH_ADD_A,
	/** (>>=, -=) **/										RSH_SUB_A,
	/** (>>=, *=) **/										RSH_MUL_A,
	/** (>>=, /=) **/										RSH_DIV_A,
	/** (>>=, %=) **/										RSH_MOD_A,
	/* shifting-bitwise-assignment (OSBA) */
	/** (<<=, &=) **/										LSH_BAN_A,
	/** (<<=, |=) **/										LSH_BOR_A,
	/** (<<=, ^=) **/										LSH_BXR_A,
	/** (>>=, &=) **/										RSH_BAN_A,
	/** (>>=, |=) **/										RSH_BOR_A,
	/** (>>=, ^=) **/										RSH_BXR_A,
	/* shifting-shifting-assignment (OSSA) */
	/** (<<=, >>=) **/										LSH_RSH_A,
	/** (>>=, <<=) **/										RSH_LSH_A,
	
	/* reference-replacement */
	/** (c, 0) **/											CST_TOT_ZRO,
	/** (c, +1) **/											CST_POS_ONE,
	/** (c, -1) **/											CST_NEG_ONE,
	/** (c, c+1) **/										CST_INC_ONE,
	/** (c, c-1) **/										CST_DEC_ONE,
	/** (c, -c)  **/										CST_NEG_CST,
	/** (c, c') **/											CST_TOT_CST,
	/** (c, v) **/											CST_TOT_REF,
	/** (v, v) **/											REF_TOT_REF,
	/** (f, f) **/											FLD_TOT_FLD,
	
	/* value-mutation */
	/** x |--> succ(x) **/									SUCC_VAL,
	/** x |--> pred(x) **/									PRED_VAL,
	/** x |--> abs(x) **/									ABS_VAL,
	/** be |--> true **/									MUT_TRUE,
	/** be |--> false **/									MUT_FALSE,
	/** trap_on_positive(x) **/								TRAP_ON_POS,
	/** trap_on_zero(x) **/									TRAP_ON_ZRO,
	/** trap_on_negative(x) **/								TRAP_ON_NEG,
	
}
