package com.jcsa.jcparse.lang.ir.stmt.assign;

import com.jcsa.jcparse.lang.ir.expr.refer.CirTemporalExpression;
import com.jcsa.jcparse.lang.ir.expr.value.CirWaitValueExpression;

/**
 * temporal_reference := wait_value_expression
 * 
 * @author yukimula
 *
 */
public interface CirWaitAssignStatement extends CirAssignStatement {
	
	/**
	 * @return 	the temporal variable to preserve the return-value 
	 * 			after calling the function callee.
	 */
	public CirTemporalExpression get_lreference();
	
	/**
	 * @return 	the waiting-value expression that describes the 
	 * 			value to be generated by some return-assignment
	 * 			during calling the function callee.
	 */
	public CirWaitValueExpression get_rexpression();
	
}
