package com.jcsa.jcmuta;

/**
 * Definition of mutation operator in AST tree.
 * @author yukimula
 *
 */
public enum MutaOperator {
	
	/* trapping mutation operators */
	/** condition_stmt.expr, bool_expression **/	trap_on_true,
	/** condition_stmt.expr, bool_expression **/	trap_on_false,
	/** case_statement.expression, expression **/	trap_on_case,
	/** expression **/								trap_on_expression,
	/** statement **/								trap_on_statement,
	/** loop_statement, integer **/					trap_at_statement,
	/** int|real_expression **/						trap_on_pos, 
	/** int|real_expression **/						trap_on_neg, 
	/** int|real_expression **/						trap_on_zro, 
	
	/* statement mutation operators */
	/** break_statement in loops **/				break_to_continue,
	/** continue_statement in loops **/				continue_to_break,
	/** statement in loop or switch **/				ins_break,
	/** statement in loop **/						ins_continue,
	/** do_while_statement **/						do_to_while,
	/** while_statement **/							while_to_do,
	/** goto_statement, label **/					set_goto_label,
	/** statement **/								delete_statement,
	/** binary_expression, index **/				delete_operand,
	/** comma_expression, index **/					delete_element,
	/** return_statement, return_statement **/		set_return_value,
	
	/* unary operator mutation operators */
	/** prev_inc_expression **/						prev_inc_to_prev_dec,
	/** prev_inc_expression **/						prev_inc_to_post_inc,
	/** prev_inc_expression **/						prev_inc_to_post_dec,
	/** prev_dec_expression **/						prev_dec_to_prev_inc,
	/** prev_dec_expression **/						prev_dec_to_post_inc,
	/** prev_dec_expression **/						prev_dec_to_post_dec,
	/** post_inc_expression **/						post_inc_to_post_dec,
	/** post_inc_expression **/						post_inc_to_prev_inc,
	/** post_inc_expression **/						post_inc_to_prev_dec,
	/** post_dec_expression **/						post_dec_to_post_inc,
	/** post_dec_expression **/						post_dec_to_prev_inc,
	/** post_dec_expression **/						post_dec_to_prev_dec,
	/** int | real | pointer reference **/			insert_prev_inc,
	/** int | real | pointer reference **/			insert_post_inc,
	/** int | real | pointer reference **/			insert_prev_dec,
	/** int | real | pointer reference **/			insert_post_dec,
	/** prev_inc_expression **/						delete_prev_inc,
	/** post_inc_expression **/						delete_post_inc,
	/** prev_dec_expression **/						delete_prev_dec,
	/** post_dec_expression **/						delete_post_dec,
	/** int expression, integer **/					inc_value,
	/** real expression, real **/					mul_value,
	insert_arith_neg,
	insert_bitws_rsv,
	insert_logic_not,
	insert_abs,
	insert_neg_abs,
	delete_arith_neg,
	delete_bitws_rsv,
	delete_logic_not,
	
	/* OAXN */
	arith_add_to_arith_sub,
	arith_add_to_arith_mul,
	arith_add_to_arith_div,
	arith_add_to_arith_mod,
	arith_add_to_bitws_and,
	arith_add_to_bitws_ior,
	arith_add_to_bitws_xor,
	arith_add_to_bitws_lsh,
	arith_add_to_bitws_rsh,
	arith_add_to_logic_and,
	arith_add_to_logic_ior,
	arith_add_to_greater_tn,
	arith_add_to_greater_eq,
	arith_add_to_smaller_tn,
	arith_add_to_smaller_eq,
	arith_add_to_equal_with,
	arith_add_to_not_equals,
	
	arith_sub_to_arith_add,
	arith_sub_to_arith_mul,
	arith_sub_to_arith_div,
	arith_sub_to_arith_mod,
	arith_sub_to_bitws_and,
	arith_sub_to_bitws_ior,
	arith_sub_to_bitws_xor,
	arith_sub_to_bitws_lsh,
	arith_sub_to_bitws_rsh,
	arith_sub_to_logic_and,
	arith_sub_to_logic_ior,
	arith_sub_to_greater_tn,
	arith_sub_to_greater_eq,
	arith_sub_to_smaller_tn,
	arith_sub_to_smaller_eq,
	arith_sub_to_equal_with,
	arith_sub_to_not_equals,
	
	arith_mul_to_arith_add,
	arith_mul_to_arith_sub,
	arith_mul_to_arith_div,
	arith_mul_to_arith_mod,
	arith_mul_to_bitws_and,
	arith_mul_to_bitws_ior,
	arith_mul_to_bitws_xor,
	arith_mul_to_bitws_lsh,
	arith_mul_to_bitws_rsh,
	arith_mul_to_logic_and,
	arith_mul_to_logic_ior,
	arith_mul_to_greater_tn,
	arith_mul_to_greater_eq,
	arith_mul_to_smaller_tn,
	arith_mul_to_smaller_eq,
	arith_mul_to_equal_with,
	arith_mul_to_not_equals,
	
	arith_div_to_arith_add,
	arith_div_to_arith_sub,
	arith_div_to_arith_mul,
	arith_div_to_arith_mod,
	arith_div_to_bitws_and,
	arith_div_to_bitws_ior,
	arith_div_to_bitws_xor,
	arith_div_to_bitws_lsh,
	arith_div_to_bitws_rsh,
	arith_div_to_logic_and,
	arith_div_to_logic_ior,
	arith_div_to_greater_tn,
	arith_div_to_greater_eq,
	arith_div_to_smaller_tn,
	arith_div_to_smaller_eq,
	arith_div_to_equal_with,
	arith_div_to_not_equals,
	
	arith_mod_to_arith_add,
	arith_mod_to_arith_sub,
	arith_mod_to_arith_mul,
	arith_mod_to_arith_div,
	arith_mod_to_bitws_and,
	arith_mod_to_bitws_ior,
	arith_mod_to_bitws_xor,
	arith_mod_to_bitws_lsh,
	arith_mod_to_bitws_rsh,
	arith_mod_to_logic_and,
	arith_mod_to_logic_ior,
	arith_mod_to_greater_tn,
	arith_mod_to_greater_eq,
	arith_mod_to_smaller_tn,
	arith_mod_to_smaller_eq,
	arith_mod_to_equal_with,
	arith_mod_to_not_equals,
	
	/* OBXN */
	bitws_and_to_arith_add,
	bitws_and_to_arith_sub,
	bitws_and_to_arith_mul,
	bitws_and_to_arith_div,
	bitws_and_to_arith_mod,
	bitws_and_to_bitws_ior,
	bitws_and_to_bitws_xor,
	bitws_and_to_bitws_lsh,
	bitws_and_to_bitws_rsh,
	bitws_and_to_logic_and,
	bitws_and_to_logic_ior,
	bitws_and_to_greater_tn,
	bitws_and_to_greater_eq,
	bitws_and_to_smaller_tn,
	bitws_and_to_smaller_eq,
	bitws_and_to_equal_with,
	bitws_and_to_not_equals,
	
	bitws_ior_to_arith_add,
	bitws_ior_to_arith_sub,
	bitws_ior_to_arith_mul,
	bitws_ior_to_arith_div,
	bitws_ior_to_arith_mod,
	bitws_ior_to_bitws_and,
	bitws_ior_to_bitws_xor,
	bitws_ior_to_bitws_lsh,
	bitws_ior_to_bitws_rsh,
	bitws_ior_to_logic_and,
	bitws_ior_to_logic_ior,
	bitws_ior_to_greater_tn,
	bitws_ior_to_greater_eq,
	bitws_ior_to_smaller_tn,
	bitws_ior_to_smaller_eq,
	bitws_ior_to_equal_with,
	bitws_ior_to_not_equals,
	
	bitws_xor_to_arith_add,
	bitws_xor_to_arith_sub,
	bitws_xor_to_arith_mul,
	bitws_xor_to_arith_div,
	bitws_xor_to_arith_mod,
	bitws_xor_to_bitws_and,
	bitws_xor_to_bitws_ior,
	bitws_xor_to_bitws_lsh,
	bitws_xor_to_bitws_rsh,
	bitws_xor_to_logic_and,
	bitws_xor_to_logic_ior,
	bitws_xor_to_greater_tn,
	bitws_xor_to_greater_eq,
	bitws_xor_to_smaller_tn,
	bitws_xor_to_smaller_eq,
	bitws_xor_to_equal_with,
	bitws_xor_to_not_equals,
	
	bitws_lsh_to_arith_add,
	bitws_lsh_to_arith_sub,
	bitws_lsh_to_arith_mul,
	bitws_lsh_to_arith_div,
	bitws_lsh_to_arith_mod,
	bitws_lsh_to_bitws_and,
	bitws_lsh_to_bitws_ior,
	bitws_lsh_to_bitws_xor,
	bitws_lsh_to_bitws_rsh,
	bitws_lsh_to_logic_and,
	bitws_lsh_to_logic_ior,
	bitws_lsh_to_greater_tn,
	bitws_lsh_to_greater_eq,
	bitws_lsh_to_smaller_tn,
	bitws_lsh_to_smaller_eq,
	bitws_lsh_to_equal_with,
	bitws_lsh_to_not_equals,
	
	bitws_rsh_to_arith_add,
	bitws_rsh_to_arith_sub,
	bitws_rsh_to_arith_mul,
	bitws_rsh_to_arith_div,
	bitws_rsh_to_arith_mod,
	bitws_rsh_to_bitws_and,
	bitws_rsh_to_bitws_ior,
	bitws_rsh_to_bitws_xor,
	bitws_rsh_to_bitws_lsh,
	bitws_rsh_to_logic_and,
	bitws_rsh_to_logic_ior,
	bitws_rsh_to_greater_tn,
	bitws_rsh_to_greater_eq,
	bitws_rsh_to_smaller_tn,
	bitws_rsh_to_smaller_eq,
	bitws_rsh_to_equal_with,
	bitws_rsh_to_not_equals,
	
	/* OLXN */
	logic_and_to_arith_add,
	logic_and_to_arith_sub,
	logic_and_to_arith_mul,
	logic_and_to_arith_div,
	logic_and_to_arith_mod,
	logic_and_to_bitws_and,
	logic_and_to_bitws_ior,
	logic_and_to_bitws_xor,
	logic_and_to_bitws_lsh,
	logic_and_to_bitws_rsh,
	logic_and_to_logic_ior,
	logic_and_to_greater_tn,
	logic_and_to_greater_eq,
	logic_and_to_smaller_tn,
	logic_and_to_smaller_eq,
	logic_and_to_equal_with,
	logic_and_to_not_equals,
	
	logic_ior_to_arith_add,
	logic_ior_to_arith_sub,
	logic_ior_to_arith_mul,
	logic_ior_to_arith_div,
	logic_ior_to_arith_mod,
	logic_ior_to_bitws_and,
	logic_ior_to_bitws_ior,
	logic_ior_to_bitws_xor,
	logic_ior_to_bitws_lsh,
	logic_ior_to_bitws_rsh,
	logic_ior_to_logic_and,
	logic_ior_to_greater_tn,
	logic_ior_to_greater_eq,
	logic_ior_to_smaller_tn,
	logic_ior_to_smaller_eq,
	logic_ior_to_equal_with,
	logic_ior_to_not_equals,
	
	/* ORXN */
	greater_tn_to_arith_add,
	greater_tn_to_arith_sub,
	greater_tn_to_arith_mul,
	greater_tn_to_arith_div,
	greater_tn_to_arith_mod,
	greater_tn_to_bitws_and,
	greater_tn_to_bitws_ior,
	greater_tn_to_bitws_xor,
	greater_tn_to_bitws_lsh,
	greater_tn_to_bitws_rsh,
	greater_tn_to_logic_and,
	greater_tn_to_logic_ior,
	greater_tn_to_greater_eq,
	greater_tn_to_smaller_tn,
	greater_tn_to_smaller_eq,
	greater_tn_to_equal_with,
	greater_tn_to_not_equals,
	
	greater_eq_to_arith_add,
	greater_eq_to_arith_sub,
	greater_eq_to_arith_mul,
	greater_eq_to_arith_div,
	greater_eq_to_arith_mod,
	greater_eq_to_bitws_and,
	greater_eq_to_bitws_ior,
	greater_eq_to_bitws_xor,
	greater_eq_to_bitws_lsh,
	greater_eq_to_bitws_rsh,
	greater_eq_to_logic_and,
	greater_eq_to_logic_ior,
	greater_eq_to_greater_tn,
	greater_eq_to_smaller_tn,
	greater_eq_to_smaller_eq,
	greater_eq_to_equal_with,
	greater_eq_to_not_equals,
	
	smaller_tn_to_arith_add,
	smaller_tn_to_arith_sub,
	smaller_tn_to_arith_mul,
	smaller_tn_to_arith_div,
	smaller_tn_to_arith_mod,
	smaller_tn_to_bitws_and,
	smaller_tn_to_bitws_ior,
	smaller_tn_to_bitws_xor,
	smaller_tn_to_bitws_lsh,
	smaller_tn_to_bitws_rsh,
	smaller_tn_to_logic_and,
	smaller_tn_to_logic_ior,
	smaller_tn_to_greater_tn,
	smaller_tn_to_greater_eq,
	smaller_tn_to_smaller_eq,
	smaller_tn_to_equal_with,
	smaller_tn_to_not_equals,
	
	smaller_eq_to_arith_add,
	smaller_eq_to_arith_sub,
	smaller_eq_to_arith_mul,
	smaller_eq_to_arith_div,
	smaller_eq_to_arith_mod,
	smaller_eq_to_bitws_and,
	smaller_eq_to_bitws_ior,
	smaller_eq_to_bitws_xor,
	smaller_eq_to_bitws_lsh,
	smaller_eq_to_bitws_rsh,
	smaller_eq_to_logic_and,
	smaller_eq_to_logic_ior,
	smaller_eq_to_greater_tn,
	smaller_eq_to_greater_eq,
	smaller_eq_to_smaller_tn,
	smaller_eq_to_equal_with,
	smaller_eq_to_not_equals,
	
	equal_with_to_arith_add,
	equal_with_to_arith_sub,
	equal_with_to_arith_mul,
	equal_with_to_arith_div,
	equal_with_to_arith_mod,
	equal_with_to_bitws_and,
	equal_with_to_bitws_ior,
	equal_with_to_bitws_xor,
	equal_with_to_bitws_lsh,
	equal_with_to_bitws_rsh,
	equal_with_to_logic_and,
	equal_with_to_logic_ior,
	equal_with_to_greater_tn,
	equal_with_to_greater_eq,
	equal_with_to_smaller_tn,
	equal_with_to_smaller_eq,
	equal_with_to_not_equals,
	
	not_equals_to_arith_add,
	not_equals_to_arith_sub,
	not_equals_to_arith_mul,
	not_equals_to_arith_div,
	not_equals_to_arith_mod,
	not_equals_to_bitws_and,
	not_equals_to_bitws_ior,
	not_equals_to_bitws_xor,
	not_equals_to_bitws_lsh,
	not_equals_to_bitws_rsh,
	not_equals_to_logic_and,
	not_equals_to_logic_ior,
	not_equals_to_greater_tn,
	not_equals_to_greater_eq,
	not_equals_to_smaller_tn,
	not_equals_to_smaller_eq,
	not_equals_to_equal_with,
	
	/* OEXA */
	assign_to_arith_add_assign,
	assign_to_arith_sub_assign,
	assign_to_arith_mul_assign,
	assign_to_arith_div_assign,
	assign_to_arith_mod_assign,
	assign_to_bitws_and_assign,
	assign_to_bitws_ior_assign,
	assign_to_bitws_xor_assign,
	assign_to_bitws_lsh_assign,
	assign_to_bitws_rsh_assign,
	
	/* OAXA */
	arith_add_assign_to_assign,
	arith_add_assign_to_arith_sub_assign,
	arith_add_assign_to_arith_mul_assign,
	arith_add_assign_to_arith_div_assign,
	arith_add_assign_to_arith_mod_assign,
	arith_add_assign_to_bitws_and_assign,
	arith_add_assign_to_bitws_ior_assign,
	arith_add_assign_to_bitws_xor_assign,
	arith_add_assign_to_bitws_lsh_assign,
	arith_add_assign_to_bitws_rsh_assign,
	
	arith_sub_assign_to_assign,
	arith_sub_assign_to_arith_add_assign,
	arith_sub_assign_to_arith_mul_assign,
	arith_sub_assign_to_arith_div_assign,
	arith_sub_assign_to_arith_mod_assign,
	arith_sub_assign_to_bitws_and_assign,
	arith_sub_assign_to_bitws_ior_assign,
	arith_sub_assign_to_bitws_xor_assign,
	arith_sub_assign_to_bitws_lsh_assign,
	arith_sub_assign_to_bitws_rsh_assign,
	
	arith_mul_assign_to_assign,
	arith_mul_assign_to_arith_add_assign,
	arith_mul_assign_to_arith_sub_assign,
	arith_mul_assign_to_arith_div_assign,
	arith_mul_assign_to_arith_mod_assign,
	arith_mul_assign_to_bitws_and_assign,
	arith_mul_assign_to_bitws_ior_assign,
	arith_mul_assign_to_bitws_xor_assign,
	arith_mul_assign_to_bitws_lsh_assign,
	arith_mul_assign_to_bitws_rsh_assign,
	
	arith_div_assign_to_assign,
	arith_div_assign_to_arith_add_assign,
	arith_div_assign_to_arith_sub_assign,
	arith_div_assign_to_arith_mul_assign,
	arith_div_assign_to_arith_mod_assign,
	arith_div_assign_to_bitws_and_assign,
	arith_div_assign_to_bitws_ior_assign,
	arith_div_assign_to_bitws_xor_assign,
	arith_div_assign_to_bitws_lsh_assign,
	arith_div_assign_to_bitws_rsh_assign,
	
	arith_mod_assign_to_assign,
	arith_mod_assign_to_arith_add_assign,
	arith_mod_assign_to_arith_sub_assign,
	arith_mod_assign_to_arith_mul_assign,
	arith_mod_assign_to_arith_div_assign,
	arith_mod_assign_to_bitws_and_assign,
	arith_mod_assign_to_bitws_ior_assign,
	arith_mod_assign_to_bitws_xor_assign,
	arith_mod_assign_to_bitws_lsh_assign,
	arith_mod_assign_to_bitws_rsh_assign,
	
	/* OBXA */
	bitws_and_assign_to_assign,
	bitws_and_assign_to_arith_add_assign,
	bitws_and_assign_to_arith_sub_assign,
	bitws_and_assign_to_arith_mul_assign,
	bitws_and_assign_to_arith_div_assign,
	bitws_and_assign_to_arith_mod_assign,
	bitws_and_assign_to_bitws_and_assign,
	bitws_and_assign_to_bitws_ior_assign,
	bitws_and_assign_to_bitws_xor_assign,
	bitws_and_assign_to_bitws_lsh_assign,
	bitws_and_assign_to_bitws_rsh_assign,
	
	bitws_ior_assign_to_assign,
	bitws_ior_assign_to_arith_add_assign,
	bitws_ior_assign_to_arith_sub_assign,
	bitws_ior_assign_to_arith_mul_assign,
	bitws_ior_assign_to_arith_div_assign,
	bitws_ior_assign_to_arith_mod_assign,
	bitws_ior_assign_to_bitws_and_assign,
	bitws_ior_assign_to_bitws_ior_assign,
	bitws_ior_assign_to_bitws_xor_assign,
	bitws_ior_assign_to_bitws_lsh_assign,
	bitws_ior_assign_to_bitws_rsh_assign,
	
	bitws_xor_assign_to_assign,
	bitws_xor_assign_to_arith_add_assign,
	bitws_xor_assign_to_arith_sub_assign,
	bitws_xor_assign_to_arith_mul_assign,
	bitws_xor_assign_to_arith_div_assign,
	bitws_xor_assign_to_arith_mod_assign,
	bitws_xor_assign_to_bitws_and_assign,
	bitws_xor_assign_to_bitws_ior_assign,
	bitws_xor_assign_to_bitws_xor_assign,
	bitws_xor_assign_to_bitws_lsh_assign,
	bitws_xor_assign_to_bitws_rsh_assign,
	
	bitws_lsh_assign_to_assign,
	bitws_lsh_assign_to_arith_add_assign,
	bitws_lsh_assign_to_arith_sub_assign,
	bitws_lsh_assign_to_arith_mul_assign,
	bitws_lsh_assign_to_arith_div_assign,
	bitws_lsh_assign_to_arith_mod_assign,
	bitws_lsh_assign_to_bitws_and_assign,
	bitws_lsh_assign_to_bitws_ior_assign,
	bitws_lsh_assign_to_bitws_xor_assign,
	bitws_lsh_assign_to_bitws_lsh_assign,
	bitws_lsh_assign_to_bitws_rsh_assign,
	
	bitws_rsh_assign_to_assign,
	bitws_rsh_assign_to_arith_add_assign,
	bitws_rsh_assign_to_arith_sub_assign,
	bitws_rsh_assign_to_arith_mul_assign,
	bitws_rsh_assign_to_arith_div_assign,
	bitws_rsh_assign_to_arith_mod_assign,
	bitws_rsh_assign_to_bitws_and_assign,
	bitws_rsh_assign_to_bitws_ior_assign,
	bitws_rsh_assign_to_bitws_xor_assign,
	bitws_rsh_assign_to_bitws_lsh_assign,
	bitws_rsh_assign_to_bitws_rsh_assign,
	
	/* value mutation class */
	/** expr as condition | bool-expr **/	set_true,
	/** expr as condition | bool-expr **/	set_false,
	/** expr as constant **/				set_constant,
	/** int | real | pointer reference **/	set_reference,
	
	/* semantic mutation operators */
	equal_with_to_assign,
	/** if | while | do..while | for **/	ins_empty_body,
	/** else if --> if (not last) **/		ins_elif_in_if,
	/** else if --> else (last)**/			set_elif_as_else,
	/** switch_stmt without default **/		ins_default,
	/** last case_stmt without default **/	set_default,
	equal_with_to_real_compare,
	not_equals_to_real_compare,
	
}
